### PR TITLE
added css to the already existing index.html. Merge it to the main branch. Doing from github second accound "Dhyani-repo"

### PR DESCRIPTION
**Pull request by Dhyani-Repo**

### CODE REVIEW

**Comment by Devender-Dhyani** [comment]
This is not the correct css that i want to add in my main branch add some relevent css

**Comment by Devender-Dhyani** [comment]
code is not appropriate

**Comment by Dhyani-Repo** [comment]
This pr is just for testing wheather css is working or not

**Comment by Devender-Dhyani** [comment]
ok. lts see

**Pull request closed without merging**
